// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: executions.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExecution = `-- name: CreateExecution :one
INSERT INTO executions (
    profile_id,
    status,
    created_at
) VALUES (
    $1,
    $2,
    now()
)
RETURNING id, profile_id, status, start_time, end_time, duration, size, checksum, storage_path, logs, error_message, is_pinned, created_at
`

type CreateExecutionParams struct {
	ProfileID pgtype.UUID
	Status    string
}

func (q *Queries) CreateExecution(ctx context.Context, arg CreateExecutionParams) (Execution, error) {
	row := q.db.QueryRow(ctx, createExecution, arg.ProfileID, arg.Status)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Status,
		&i.StartTime,
		&i.EndTime,
		&i.Duration,
		&i.Size,
		&i.Checksum,
		&i.StoragePath,
		&i.Logs,
		&i.ErrorMessage,
		&i.IsPinned,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExecution = `-- name: DeleteExecution :exec
DELETE FROM executions
WHERE id = $1
`

func (q *Queries) DeleteExecution(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteExecution, id)
	return err
}

const getExecution = `-- name: GetExecution :one
SELECT id, profile_id, status, start_time, end_time, duration, size, checksum, storage_path, logs, error_message, is_pinned, created_at
FROM executions
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetExecution(ctx context.Context, id pgtype.UUID) (Execution, error) {
	row := q.db.QueryRow(ctx, getExecution, id)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Status,
		&i.StartTime,
		&i.EndTime,
		&i.Duration,
		&i.Size,
		&i.Checksum,
		&i.StoragePath,
		&i.Logs,
		&i.ErrorMessage,
		&i.IsPinned,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestExecution = `-- name: GetLatestExecution :one
SELECT id, profile_id, status, start_time, end_time, duration, size, checksum, storage_path, logs, error_message, is_pinned, created_at
FROM executions
WHERE profile_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestExecution(ctx context.Context, profileID pgtype.UUID) (Execution, error) {
	row := q.db.QueryRow(ctx, getLatestExecution, profileID)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Status,
		&i.StartTime,
		&i.EndTime,
		&i.Duration,
		&i.Size,
		&i.Checksum,
		&i.StoragePath,
		&i.Logs,
		&i.ErrorMessage,
		&i.IsPinned,
		&i.CreatedAt,
	)
	return i, err
}

const listExecutionsByProfile = `-- name: ListExecutionsByProfile :many
SELECT id, profile_id, status, start_time, end_time, duration, size, checksum, storage_path, logs, error_message, is_pinned, created_at
FROM executions
WHERE profile_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListExecutionsByProfile(ctx context.Context, profileID pgtype.UUID) ([]Execution, error) {
	rows, err := q.db.Query(ctx, listExecutionsByProfile, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Execution
	for rows.Next() {
		var i Execution
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.Status,
			&i.StartTime,
			&i.EndTime,
			&i.Duration,
			&i.Size,
			&i.Checksum,
			&i.StoragePath,
			&i.Logs,
			&i.ErrorMessage,
			&i.IsPinned,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setExecutionPinned = `-- name: SetExecutionPinned :exec
UPDATE executions
SET is_pinned = $2
WHERE id = $1
`

type SetExecutionPinnedParams struct {
	ID       pgtype.UUID
	IsPinned bool
}

func (q *Queries) SetExecutionPinned(ctx context.Context, arg SetExecutionPinnedParams) error {
	_, err := q.db.Exec(ctx, setExecutionPinned, arg.ID, arg.IsPinned)
	return err
}

const updateExecution = `-- name: UpdateExecution :one
UPDATE executions
SET
    status = $2,
    start_time = $3,
    end_time = $4,
    duration = $5,
    size = $6,
    checksum = $7,
    storage_path = $8,
    logs = $9,
    error_message = $10,
    is_pinned = $11
WHERE id = $1
RETURNING id, profile_id, status, start_time, end_time, duration, size, checksum, storage_path, logs, error_message, is_pinned, created_at
`

type UpdateExecutionParams struct {
	ID           pgtype.UUID
	Status       string
	StartTime    pgtype.Timestamptz
	EndTime      pgtype.Timestamptz
	Duration     pgtype.Interval
	Size         pgtype.Int8
	Checksum     pgtype.Text
	StoragePath  pgtype.Text
	Logs         json.RawMessage
	ErrorMessage pgtype.Text
	IsPinned     bool
}

func (q *Queries) UpdateExecution(ctx context.Context, arg UpdateExecutionParams) (Execution, error) {
	row := q.db.QueryRow(ctx, updateExecution,
		arg.ID,
		arg.Status,
		arg.StartTime,
		arg.EndTime,
		arg.Duration,
		arg.Size,
		arg.Checksum,
		arg.StoragePath,
		arg.Logs,
		arg.ErrorMessage,
		arg.IsPinned,
	)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Status,
		&i.StartTime,
		&i.EndTime,
		&i.Duration,
		&i.Size,
		&i.Checksum,
		&i.StoragePath,
		&i.Logs,
		&i.ErrorMessage,
		&i.IsPinned,
		&i.CreatedAt,
	)
	return i, err
}
