// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type Execution struct {
	ID           pgtype.UUID
	ProfileID    pgtype.UUID
	Status       string
	StartTime    pgtype.Timestamptz
	EndTime      pgtype.Timestamptz
	Duration     pgtype.Interval
	Size         pgtype.Int8
	Checksum     pgtype.Text
	StoragePath  pgtype.Text
	Logs         json.RawMessage
	ErrorMessage pgtype.Text
	IsPinned     bool
	CreatedAt    pgtype.Timestamptz
}

type NotificationProvider struct {
	ID        pgtype.UUID
	Name      string
	Type      string
	Config    json.RawMessage
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Profile struct {
	ID                pgtype.UUID
	Name              string
	Description       pgtype.Text
	Enabled           bool
	Schedule          string
	RetentionPolicyID pgtype.UUID
	CompressionType   string
	CompressionLevel  int32
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type ProfileNotificationProvider struct {
	ProfileID              pgtype.UUID
	NotificationProviderID pgtype.UUID
}

type ProfileStorageProvider struct {
	ProfileID         pgtype.UUID
	StorageProviderID pgtype.UUID
}

type RetentionPolicy struct {
	ID          pgtype.UUID
	Name        string
	KeepHourly  int32
	KeepDaily   int32
	KeepWeekly  int32
	KeepMonthly int32
	KeepYearly  int32
	YearlyMonth int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type StorageProvider struct {
	ID        pgtype.UUID
	Name      string
	Type      string
	Config    json.RawMessage
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
