// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_provider.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNotificationProvider = `-- name: CreateNotificationProvider :one
INSERT INTO notification_providers (
    id,
    name,
    type,
    config
) VALUES (
    $1,$2,$3,$4
)
RETURNING id, name, type, config, created_at, updated_at
`

type CreateNotificationProviderParams struct {
	ID     pgtype.UUID
	Name   string
	Type   string
	Config []byte
}

func (q *Queries) CreateNotificationProvider(ctx context.Context, arg CreateNotificationProviderParams) (NotificationProvider, error) {
	row := q.db.QueryRow(ctx, createNotificationProvider,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Config,
	)
	var i NotificationProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNotificationProvider = `-- name: DeleteNotificationProvider :exec
DELETE FROM notification_providers
WHERE id = $1
`

func (q *Queries) DeleteNotificationProvider(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteNotificationProvider, id)
	return err
}

const getNotificationProvider = `-- name: GetNotificationProvider :one
SELECT id, name, type, config, created_at, updated_at
FROM notification_providers
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetNotificationProvider(ctx context.Context, id pgtype.UUID) (NotificationProvider, error) {
	row := q.db.QueryRow(ctx, getNotificationProvider, id)
	var i NotificationProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNotificationProviders = `-- name: ListNotificationProviders :many
SELECT id, name, type, config, created_at, updated_at
FROM notification_providers
ORDER BY name
`

func (q *Queries) ListNotificationProviders(ctx context.Context) ([]NotificationProvider, error) {
	rows, err := q.db.Query(ctx, listNotificationProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationProvider
	for rows.Next() {
		var i NotificationProvider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotificationProvider = `-- name: UpdateNotificationProvider :one
UPDATE notification_providers
SET
    name = $2,
    type = $3,
    config = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, name, type, config, created_at, updated_at
`

type UpdateNotificationProviderParams struct {
	ID     pgtype.UUID
	Name   string
	Type   string
	Config []byte
}

func (q *Queries) UpdateNotificationProvider(ctx context.Context, arg UpdateNotificationProviderParams) (NotificationProvider, error) {
	row := q.db.QueryRow(ctx, updateNotificationProvider,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Config,
	)
	var i NotificationProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
