// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateProfile = `-- name: ActivateProfile :exec
UPDATE profiles
SET enabled = CASE
    WHEN id = $1 THEN true
    ELSE false
END
`

func (q *Queries) ActivateProfile(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, activateProfile, id)
	return err
}

const addProfileNotificationProvider = `-- name: AddProfileNotificationProvider :exec
INSERT INTO profile_notification_providers (profile_id, notification_provider_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddProfileNotificationProviderParams struct {
	ProfileID              pgtype.UUID
	NotificationProviderID pgtype.UUID
}

func (q *Queries) AddProfileNotificationProvider(ctx context.Context, arg AddProfileNotificationProviderParams) error {
	_, err := q.db.Exec(ctx, addProfileNotificationProvider, arg.ProfileID, arg.NotificationProviderID)
	return err
}

const addProfileStorageProvider = `-- name: AddProfileStorageProvider :exec
INSERT INTO profile_storage_providers (profile_id, storage_provider_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddProfileStorageProviderParams struct {
	ProfileID         pgtype.UUID
	StorageProviderID pgtype.UUID
}

func (q *Queries) AddProfileStorageProvider(ctx context.Context, arg AddProfileStorageProviderParams) error {
	_, err := q.db.Exec(ctx, addProfileStorageProvider, arg.ProfileID, arg.StorageProviderID)
	return err
}

const clearProfileNotificationProviders = `-- name: ClearProfileNotificationProviders :exec
DELETE FROM profile_notification_providers
WHERE profile_id = $1
`

func (q *Queries) ClearProfileNotificationProviders(ctx context.Context, profileID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearProfileNotificationProviders, profileID)
	return err
}

const clearProfileStorageProviders = `-- name: ClearProfileStorageProviders :exec
DELETE FROM profile_storage_providers
WHERE profile_id = $1
`

func (q *Queries) ClearProfileStorageProviders(ctx context.Context, profileID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearProfileStorageProviders, profileID)
	return err
}

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (
    name,
    description,
    enabled,
    schedule,
    retention_policy_id,
    compression_type,
    compression_level,
    encryption_enabled
) VALUES (
    $1,$2,$3,$4,$5,$6,$7,$8
)
RETURNING id, name, description, enabled, schedule, retention_policy_id, compression_type, compression_level, created_at, updated_at, encryption_enabled
`

type CreateProfileParams struct {
	Name              string
	Description       pgtype.Text
	Enabled           bool
	Schedule          string
	RetentionPolicyID pgtype.UUID
	CompressionType   string
	CompressionLevel  int32
	EncryptionEnabled bool
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, createProfile,
		arg.Name,
		arg.Description,
		arg.Enabled,
		arg.Schedule,
		arg.RetentionPolicyID,
		arg.CompressionType,
		arg.CompressionLevel,
		arg.EncryptionEnabled,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Enabled,
		&i.Schedule,
		&i.RetentionPolicyID,
		&i.CompressionType,
		&i.CompressionLevel,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EncryptionEnabled,
	)
	return i, err
}

const deleteProfile = `-- name: DeleteProfile :exec
DELETE FROM profiles
WHERE id = $1
`

func (q *Queries) DeleteProfile(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProfile, id)
	return err
}

const getProfile = `-- name: GetProfile :one
SELECT id, name, description, enabled, schedule, retention_policy_id, compression_type, compression_level, created_at, updated_at, encryption_enabled FROM profiles
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetProfile(ctx context.Context, id pgtype.UUID) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfile, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Enabled,
		&i.Schedule,
		&i.RetentionPolicyID,
		&i.CompressionType,
		&i.CompressionLevel,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EncryptionEnabled,
	)
	return i, err
}

const getProfileNotificationProviderIDs = `-- name: GetProfileNotificationProviderIDs :many
SELECT notification_provider_id FROM profile_notification_providers
WHERE profile_id = $1
`

func (q *Queries) GetProfileNotificationProviderIDs(ctx context.Context, profileID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getProfileNotificationProviderIDs, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var notification_provider_id pgtype.UUID
		if err := rows.Scan(&notification_provider_id); err != nil {
			return nil, err
		}
		items = append(items, notification_provider_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProfileStorageProviderIDs = `-- name: GetProfileStorageProviderIDs :many
SELECT storage_provider_id FROM profile_storage_providers
WHERE profile_id = $1
`

func (q *Queries) GetProfileStorageProviderIDs(ctx context.Context, profileID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getProfileStorageProviderIDs, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var storage_provider_id pgtype.UUID
		if err := rows.Scan(&storage_provider_id); err != nil {
			return nil, err
		}
		items = append(items, storage_provider_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfiles = `-- name: ListProfiles :many
SELECT id, name, description, enabled, schedule, retention_policy_id, compression_type, compression_level, created_at, updated_at, encryption_enabled FROM profiles
ORDER BY name
`

func (q *Queries) ListProfiles(ctx context.Context) ([]Profile, error) {
	rows, err := q.db.Query(ctx, listProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Profile
	for rows.Next() {
		var i Profile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Enabled,
			&i.Schedule,
			&i.RetentionPolicyID,
			&i.CompressionType,
			&i.CompressionLevel,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EncryptionEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE profiles
SET
    name = $2,
    description = $3,
    enabled = $4,
    schedule = $5,
    retention_policy_id = $6,
    compression_type = $7,
    compression_level = $8,
    encryption_enabled = $9,
    updated_at = now()
WHERE id = $1
RETURNING id, name, description, enabled, schedule, retention_policy_id, compression_type, compression_level, created_at, updated_at, encryption_enabled
`

type UpdateProfileParams struct {
	ID                pgtype.UUID
	Name              string
	Description       pgtype.Text
	Enabled           bool
	Schedule          string
	RetentionPolicyID pgtype.UUID
	CompressionType   string
	CompressionLevel  int32
	EncryptionEnabled bool
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, updateProfile,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Enabled,
		arg.Schedule,
		arg.RetentionPolicyID,
		arg.CompressionType,
		arg.CompressionLevel,
		arg.EncryptionEnabled,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Enabled,
		&i.Schedule,
		&i.RetentionPolicyID,
		&i.CompressionType,
		&i.CompressionLevel,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EncryptionEnabled,
	)
	return i, err
}
