// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateProfile = `-- name: ActivateProfile :exec
UPDATE profiles
SET enabled = CASE
    WHEN id = $1 THEN true
    ELSE false
END
`

func (q *Queries) ActivateProfile(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, activateProfile, id)
	return err
}

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (
    name,
    description,
    enabled,
    schedule,
    storage_provider_id,
    notification_provider_id,
    retention_policy_id,
    compression_type,
    compression_level
) VALUES (
    $1,$2,$3,$4,$5,$6,$7,$8,$9
)
RETURNING id, name, description, enabled, schedule, storage_provider_id, notification_provider_id, retention_policy_id, compression_type, compression_level, created_at, updated_at
`

type CreateProfileParams struct {
	Name                   string
	Description            pgtype.Text
	Enabled                bool
	Schedule               string
	StorageProviderID      pgtype.UUID
	NotificationProviderID pgtype.UUID
	RetentionPolicyID      pgtype.UUID
	CompressionType        string
	CompressionLevel       int32
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, createProfile,
		arg.Name,
		arg.Description,
		arg.Enabled,
		arg.Schedule,
		arg.StorageProviderID,
		arg.NotificationProviderID,
		arg.RetentionPolicyID,
		arg.CompressionType,
		arg.CompressionLevel,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Enabled,
		&i.Schedule,
		&i.StorageProviderID,
		&i.NotificationProviderID,
		&i.RetentionPolicyID,
		&i.CompressionType,
		&i.CompressionLevel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProfile = `-- name: DeleteProfile :exec
DELETE FROM profiles
WHERE id = $1
`

func (q *Queries) DeleteProfile(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProfile, id)
	return err
}

const getProfile = `-- name: GetProfile :one
SELECT id, name, description, enabled, schedule, storage_provider_id, notification_provider_id, retention_policy_id, compression_type, compression_level, created_at, updated_at FROM profiles
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetProfile(ctx context.Context, id pgtype.UUID) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfile, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Enabled,
		&i.Schedule,
		&i.StorageProviderID,
		&i.NotificationProviderID,
		&i.RetentionPolicyID,
		&i.CompressionType,
		&i.CompressionLevel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProfiles = `-- name: ListProfiles :many
SELECT id, name, description, enabled, schedule, storage_provider_id, notification_provider_id, retention_policy_id, compression_type, compression_level, created_at, updated_at FROM profiles
ORDER BY name
`

func (q *Queries) ListProfiles(ctx context.Context) ([]Profile, error) {
	rows, err := q.db.Query(ctx, listProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Profile
	for rows.Next() {
		var i Profile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Enabled,
			&i.Schedule,
			&i.StorageProviderID,
			&i.NotificationProviderID,
			&i.RetentionPolicyID,
			&i.CompressionType,
			&i.CompressionLevel,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE profiles
SET
    name = $2,
    description = $3,
    enabled = $4,
    schedule = $5,
    storage_provider_id = $6,
    notification_provider_id = $7,
    retention_policy_id = $8,
    compression_type = $9,
    compression_level = $10,
    updated_at = now()
WHERE id = $1
RETURNING id, name, description, enabled, schedule, storage_provider_id, notification_provider_id, retention_policy_id, compression_type, compression_level, created_at, updated_at
`

type UpdateProfileParams struct {
	ID                     pgtype.UUID
	Name                   string
	Description            pgtype.Text
	Enabled                bool
	Schedule               string
	StorageProviderID      pgtype.UUID
	NotificationProviderID pgtype.UUID
	RetentionPolicyID      pgtype.UUID
	CompressionType        string
	CompressionLevel       int32
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, updateProfile,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Enabled,
		arg.Schedule,
		arg.StorageProviderID,
		arg.NotificationProviderID,
		arg.RetentionPolicyID,
		arg.CompressionType,
		arg.CompressionLevel,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Enabled,
		&i.Schedule,
		&i.StorageProviderID,
		&i.NotificationProviderID,
		&i.RetentionPolicyID,
		&i.CompressionType,
		&i.CompressionLevel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
