// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retention_policy.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRetentionPolicy = `-- name: CreateRetentionPolicy :one
INSERT INTO retention_policies (
    name,
    keep_hourly,
    keep_daily,
    keep_weekly,
    keep_monthly,
    keep_yearly,
    yearly_month
) VALUES (
    $1,$2,$3,$4,$5,$6,$7
)
RETURNING id, name, keep_hourly, keep_daily, keep_weekly, keep_monthly, keep_yearly, yearly_month, created_at, updated_at
`

type CreateRetentionPolicyParams struct {
	Name        string
	KeepHourly  int32
	KeepDaily   int32
	KeepWeekly  int32
	KeepMonthly int32
	KeepYearly  int32
	YearlyMonth int32
}

func (q *Queries) CreateRetentionPolicy(ctx context.Context, arg CreateRetentionPolicyParams) (RetentionPolicy, error) {
	row := q.db.QueryRow(ctx, createRetentionPolicy,
		arg.Name,
		arg.KeepHourly,
		arg.KeepDaily,
		arg.KeepWeekly,
		arg.KeepMonthly,
		arg.KeepYearly,
		arg.YearlyMonth,
	)
	var i RetentionPolicy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeepHourly,
		&i.KeepDaily,
		&i.KeepWeekly,
		&i.KeepMonthly,
		&i.KeepYearly,
		&i.YearlyMonth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRetentionPolicy = `-- name: DeleteRetentionPolicy :exec
DELETE FROM retention_policies
WHERE id = $1
`

func (q *Queries) DeleteRetentionPolicy(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRetentionPolicy, id)
	return err
}

const getRetentionPolicy = `-- name: GetRetentionPolicy :one
SELECT id, name, keep_hourly, keep_daily, keep_weekly, keep_monthly, keep_yearly, yearly_month, created_at, updated_at
FROM retention_policies
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetRetentionPolicy(ctx context.Context, id pgtype.UUID) (RetentionPolicy, error) {
	row := q.db.QueryRow(ctx, getRetentionPolicy, id)
	var i RetentionPolicy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeepHourly,
		&i.KeepDaily,
		&i.KeepWeekly,
		&i.KeepMonthly,
		&i.KeepYearly,
		&i.YearlyMonth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRetentionPolicies = `-- name: ListRetentionPolicies :many
SELECT id, name, keep_hourly, keep_daily, keep_weekly, keep_monthly, keep_yearly, yearly_month, created_at, updated_at
FROM retention_policies
ORDER BY name
`

func (q *Queries) ListRetentionPolicies(ctx context.Context) ([]RetentionPolicy, error) {
	rows, err := q.db.Query(ctx, listRetentionPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RetentionPolicy
	for rows.Next() {
		var i RetentionPolicy
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.KeepHourly,
			&i.KeepDaily,
			&i.KeepWeekly,
			&i.KeepMonthly,
			&i.KeepYearly,
			&i.YearlyMonth,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRetentionPolicy = `-- name: UpdateRetentionPolicy :one
UPDATE retention_policies
SET
    name = $2,
    keep_hourly = $3,
    keep_daily = $4,
    keep_weekly = $5,
    keep_monthly = $6,
    keep_yearly = $7,
    yearly_month = $8,
    updated_at = now()
WHERE id = $1
RETURNING id, name, keep_hourly, keep_daily, keep_weekly, keep_monthly, keep_yearly, yearly_month, created_at, updated_at
`

type UpdateRetentionPolicyParams struct {
	ID          pgtype.UUID
	Name        string
	KeepHourly  int32
	KeepDaily   int32
	KeepWeekly  int32
	KeepMonthly int32
	KeepYearly  int32
	YearlyMonth int32
}

func (q *Queries) UpdateRetentionPolicy(ctx context.Context, arg UpdateRetentionPolicyParams) (RetentionPolicy, error) {
	row := q.db.QueryRow(ctx, updateRetentionPolicy,
		arg.ID,
		arg.Name,
		arg.KeepHourly,
		arg.KeepDaily,
		arg.KeepWeekly,
		arg.KeepMonthly,
		arg.KeepYearly,
		arg.YearlyMonth,
	)
	var i RetentionPolicy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeepHourly,
		&i.KeepDaily,
		&i.KeepWeekly,
		&i.KeepMonthly,
		&i.KeepYearly,
		&i.YearlyMonth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
