// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: storage_provider.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStorageProvider = `-- name: CreateStorageProvider :one
INSERT INTO storage_providers (
    id,
    name,
    type,
    config
) VALUES (
    $1,$2,$3,$4
)
RETURNING id, name, type, config, created_at, updated_at
`

type CreateStorageProviderParams struct {
	ID     pgtype.UUID
	Name   string
	Type   string
	Config json.RawMessage
}

func (q *Queries) CreateStorageProvider(ctx context.Context, arg CreateStorageProviderParams) (StorageProvider, error) {
	row := q.db.QueryRow(ctx, createStorageProvider,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Config,
	)
	var i StorageProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStorageProvider = `-- name: DeleteStorageProvider :exec
DELETE FROM storage_providers
WHERE id = $1
`

func (q *Queries) DeleteStorageProvider(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteStorageProvider, id)
	return err
}

const getStorageProvider = `-- name: GetStorageProvider :one
SELECT id, name, type, config, created_at, updated_at
FROM storage_providers
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetStorageProvider(ctx context.Context, id pgtype.UUID) (StorageProvider, error) {
	row := q.db.QueryRow(ctx, getStorageProvider, id)
	var i StorageProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStorageProviders = `-- name: ListStorageProviders :many
SELECT id, name, type, config, created_at, updated_at
FROM storage_providers
ORDER BY name
`

func (q *Queries) ListStorageProviders(ctx context.Context) ([]StorageProvider, error) {
	rows, err := q.db.Query(ctx, listStorageProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StorageProvider
	for rows.Next() {
		var i StorageProvider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStorageProvider = `-- name: UpdateStorageProvider :one
UPDATE storage_providers
SET
    name = $2,
    type = $3,
    config = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, name, type, config, created_at, updated_at
`

type UpdateStorageProviderParams struct {
	ID     pgtype.UUID
	Name   string
	Type   string
	Config json.RawMessage
}

func (q *Queries) UpdateStorageProvider(ctx context.Context, arg UpdateStorageProviderParams) (StorageProvider, error) {
	row := q.db.QueryRow(ctx, updateStorageProvider,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Config,
	)
	var i StorageProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
