// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/executions": {
            "get": {
                "description": "Get a history of all backup executions in the system across all profiles.\nResults are sorted by creation date (newest first).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "executions"
                ],
                "summary": "List all backup executions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_api_dto.ExecutionResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_pkg_apiutil.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/executions/{id}": {
            "get": {
                "description": "Get full details of a specific backup execution.\nThe 'logs' field contains an array of strings formatted as 'TIMESTAMP: MESSAGE'.\nThese logs provide a step-by-step trace of the backup pipeline stages.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "executions"
                ],
                "summary": "Get execution details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Execution ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_api_dto.ExecutionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_pkg_apiutil.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_pkg_apiutil.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_pkg_apiutil.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/executions/{id}/pin": {
            "post": {
                "description": "Prevent a backup execution from being automatically cleaned up by pinning it.\nPinned executions are ignored by the retention engine's deletion logic.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "executions"
                ],
                "summary": "Pin or unpin a backup execution",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Execution ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Pin status",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_api_dto.PinRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_pkg_apiutil.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_pkg_apiutil.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/executions/{id}/restore": {
            "post": {
                "description": "Trigger a restoration process from a specific backup execution",
                "tags": [
                    "executions"
                ],
                "summary": "Restore a backup",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Execution ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_pkg_apiutil.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_pkg_apiutil.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Check if the API server is up and running",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Simple health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health/summary": {
            "get": {
                "description": "Get an aggregated view of system health, storage usage, and active profiles",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Get system health summary",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_monitor.HealthSummary"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_pkg_apiutil.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/notification-providers": {
            "get": {
                "description": "Get a list of all configured notification providers.\nThe 'config' field varies by 'type':\n- 'discord': Requires {\"webhook_url\": \"https://discord.com/api/webhooks/...\"} to send alerts to a Discord channel.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notification-providers"
                ],
                "summary": "List all notification providers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_api_dto.NotificationProviderResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_pkg_apiutil.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Configure a new destination for backup alerts.\nYou must specify a 'type' and its corresponding 'config' object:\n- 'discord': Requires 'webhook_url' in the config object.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notification-providers"
                ],
                "summary": "Create a new notification provider",
                "parameters": [
                    {
                        "description": "Notification provider configuration",
                        "name": "provider",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_api_dto.NotificationProviderRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_api_dto.NotificationProviderResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_pkg_apiutil.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_pkg_apiutil.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/notification-providers/{id}": {
            "put": {
                "description": "Update a notification provider's configuration by ID.\nEnsure the 'config' object matches the 'type':\n- 'discord': {\"webhook_url\": \"https://discord.com/api/webhooks/...\"}",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notification-providers"
                ],
                "summary": "Update an existing notification provider",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Provider ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated configuration",
                        "name": "provider",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_api_dto.NotificationProviderRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_api_dto.NotificationProviderResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_pkg_apiutil.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_pkg_apiutil.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove a notification provider configuration",
                "tags": [
                    "notification-providers"
                ],
                "summary": "Delete a notification provider",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Provider ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_pkg_apiutil.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/profiles": {
            "get": {
                "description": "Get a list of all configured backup profiles.\nProfiles link databases to storage destinations via schedules.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profiles"
                ],
                "summary": "List all backup profiles",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_api_dto.ProfileResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_pkg_apiutil.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new backup profile with the specified configuration.\nRequires at least one storage_provider_ids and a retention_policy_id.\nThe schedule must be a valid cron expression (e.g., \"0 0 * * *\").",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profiles"
                ],
                "summary": "Create a new backup profile",
                "parameters": [
                    {
                        "description": "Profile configuration",
                        "name": "profile",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_api_dto.ProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_api_dto.ProfileResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_pkg_apiutil.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_pkg_apiutil.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/profiles/{id}": {
            "put": {
                "description": "Update a backup profile by its ID.\nThe schedule must be a valid cron expression:\n- \"0 * * * *\" (Hourly)\n- \"0 2 * * *\" (Daily at 2:00 AM)\n- \"0 0 * * 0\" (Weekly on Sunday)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profiles"
                ],
                "summary": "Update an existing backup profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Profile ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated profile configuration",
                        "name": "profile",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_api_dto.ProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_api_dto.ProfileResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_pkg_apiutil.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_pkg_apiutil.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a backup profile by its ID",
                "tags": [
                    "profiles"
                ],
                "summary": "Delete a backup profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Profile ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_pkg_apiutil.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_pkg_apiutil.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/profiles/{id}/activate": {
            "post": {
                "description": "Set a profile as the active one for scheduled backups.\nThis updates the system scheduler to use this profile's schedule.\nNote: The current system logic may only support one active profile at a time.",
                "tags": [
                    "profiles"
                ],
                "summary": "Activate a backup profile (sets as scheduled)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Profile ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_api_dto.ProfileResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_pkg_apiutil.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_pkg_apiutil.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/profiles/{id}/executions": {
            "get": {
                "description": "Get a history of all backup executions for a profile.\nResults are sorted by creation date (newest first).\nStatus can be: pending, running, success, failed.\nThe 'logs' field contains an array of strings formatted as 'TIMESTAMP: MESSAGE'.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "executions"
                ],
                "summary": "List executions for a specific profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Profile ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_api_dto.ExecutionResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_pkg_apiutil.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_pkg_apiutil.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/profiles/{id}/run": {
            "post": {
                "description": "Trigger an asynchronous backup execution for a specific profile now.\nThis bypasses the schedule and enqueues the job in the runner.",
                "tags": [
                    "profiles"
                ],
                "summary": "Run a backup profile immediately",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Profile ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_pkg_apiutil.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/retention-policies": {
            "get": {
                "description": "Get a list of all configured retention policies.\nPolicies define how many backups are kept for different time intervals:\n- keep_hourly: Last N hours.\n- keep_daily: Last N days.\n- keep_weekly: Last N weeks.\n- yearly_month: The month (1-12) chosen for yearly preservation.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "retention-policies"
                ],
                "summary": "List all retention policies",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_api_dto.RetentionPolicyResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_pkg_apiutil.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Define a new policy for automatic backup cleanup.\nFields define the 'Grandfather-Father-Son' retention strategy:\n- keep_daily: 7 means keep one backup per day for 7 days.\n- yearly_month: 1 means the January backup is kept as the yearly one.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "retention-policies"
                ],
                "summary": "Create a new retention policy",
                "parameters": [
                    {
                        "description": "Retention policy configuration",
                        "name": "policy",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_api_dto.RetentionPolicyRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_api_dto.RetentionPolicyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_pkg_apiutil.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_pkg_apiutil.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/retention-policies/{id}": {
            "put": {
                "description": "Update a retention policy's configuration by ID.\nAllows changing how many backups are kept at each level.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "retention-policies"
                ],
                "summary": "Update an existing retention policy",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Policy ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated configuration",
                        "name": "policy",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_api_dto.RetentionPolicyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_api_dto.RetentionPolicyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_pkg_apiutil.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_pkg_apiutil.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove a retention policy configuration",
                "tags": [
                    "retention-policies"
                ],
                "summary": "Delete a retention policy",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Policy ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_pkg_apiutil.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/storage-providers": {
            "get": {
                "description": "Get a list of all configured storage providers.\nThe 'config' field varies by 'type':\n- 'local': Use {\"path\": \"/tmp/backups\"} to define the base directory on the server.\n- 's3': Use {\"region\": \"us-east-1\", \"bucket\": \"my-backups\", \"access_key\": \"...\", \"secret_key\": \"...\"} for AWS S3 compatible storage.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "storage-providers"
                ],
                "summary": "List all storage providers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_api_dto.StorageProviderResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_pkg_apiutil.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Configure a new storage destination for backups.\nYou must specify a 'type' and its corresponding 'config' object:\n- 'local': Base directory for storing backups locally. Requires 'path'.\n- 's3': AWS S3 or compatible storage. Requires 'region', 'bucket', 'access_key', and 'secret_key'.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "storage-providers"
                ],
                "summary": "Create a new storage provider",
                "parameters": [
                    {
                        "description": "Storage provider configuration",
                        "name": "provider",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_api_dto.StorageProviderRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_api_dto.StorageProviderResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_pkg_apiutil.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_pkg_apiutil.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/storage-providers/{id}": {
            "put": {
                "description": "Update a storage provider's configuration by ID.\nEnsure the 'config' object matches the 'type':\n- 'local': {\"path\": \"/tmp/backups\"}\n- 's3': {\"region\": \"us-east-1\", \"bucket\": \"my-backups\", \"access_key\": \"...\", \"secret_key\": \"...\"}",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "storage-providers"
                ],
                "summary": "Update an existing storage provider",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Provider ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated configuration",
                        "name": "provider",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_api_dto.StorageProviderRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_api_dto.StorageProviderResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_pkg_apiutil.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_pkg_apiutil.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove a storage provider configuration",
                "tags": [
                    "storage-providers"
                ],
                "summary": "Delete a storage provider",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Provider ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_pkg_apiutil.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_MD2SA_backup-manager_internal_api_dto.ExecutionResponse": {
            "type": "object",
            "properties": {
                "checksum": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "duration": {
                    "type": "string"
                },
                "end_time": {
                    "type": "string"
                },
                "error_message": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_pinned": {
                    "type": "boolean"
                },
                "logs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "profile_id": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                },
                "start_time": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "storage_path": {
                    "type": "string"
                }
            }
        },
        "github_com_MD2SA_backup-manager_internal_api_dto.NotificationProviderRequest": {
            "type": "object",
            "required": [
                "config",
                "name",
                "type"
            ],
            "properties": {
                "config": {
                    "type": "object"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "discord"
                    ]
                }
            }
        },
        "github_com_MD2SA_backup-manager_internal_api_dto.NotificationProviderResponse": {
            "type": "object",
            "properties": {
                "config": {
                    "type": "object"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_MD2SA_backup-manager_internal_api_dto.PinRequest": {
            "type": "object",
            "properties": {
                "pinned": {
                    "type": "boolean"
                }
            }
        },
        "github_com_MD2SA_backup-manager_internal_api_dto.ProfileRequest": {
            "type": "object",
            "required": [
                "compression_type",
                "name",
                "retention_policy_id",
                "schedule",
                "storage_provider_ids"
            ],
            "properties": {
                "compression_level": {
                    "type": "integer",
                    "maximum": 9,
                    "minimum": 0
                },
                "compression_type": {
                    "type": "string",
                    "enum": [
                        "none",
                        "gzip"
                    ]
                },
                "description": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "notification_provider_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "retention_policy_id": {
                    "type": "string"
                },
                "schedule": {
                    "type": "string"
                },
                "storage_provider_ids": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "github_com_MD2SA_backup-manager_internal_api_dto.ProfileResponse": {
            "type": "object",
            "properties": {
                "compression_level": {
                    "type": "integer"
                },
                "compression_type": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "notification_provider_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "retention_policy_id": {
                    "type": "string"
                },
                "schedule": {
                    "type": "string"
                },
                "storage_provider_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_MD2SA_backup-manager_internal_api_dto.RetentionPolicyRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "keep_daily": {
                    "type": "integer",
                    "minimum": 0
                },
                "keep_hourly": {
                    "type": "integer",
                    "minimum": 0
                },
                "keep_monthly": {
                    "type": "integer",
                    "minimum": 0
                },
                "keep_weekly": {
                    "type": "integer",
                    "minimum": 0
                },
                "keep_yearly": {
                    "type": "integer",
                    "minimum": 0
                },
                "name": {
                    "type": "string"
                },
                "yearly_month": {
                    "type": "integer",
                    "maximum": 12,
                    "minimum": 1
                }
            }
        },
        "github_com_MD2SA_backup-manager_internal_api_dto.RetentionPolicyResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "keep_daily": {
                    "type": "integer"
                },
                "keep_hourly": {
                    "type": "integer"
                },
                "keep_monthly": {
                    "type": "integer"
                },
                "keep_weekly": {
                    "type": "integer"
                },
                "keep_yearly": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "yearly_month": {
                    "type": "integer"
                }
            }
        },
        "github_com_MD2SA_backup-manager_internal_api_dto.StorageProviderRequest": {
            "type": "object",
            "required": [
                "config",
                "name",
                "type"
            ],
            "properties": {
                "config": {
                    "type": "object"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "local",
                        "s3"
                    ]
                }
            }
        },
        "github_com_MD2SA_backup-manager_internal_api_dto.StorageProviderResponse": {
            "type": "object",
            "properties": {
                "config": {
                    "type": "object"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_MD2SA_backup-manager_internal_monitor.HealthStatus": {
            "type": "string",
            "enum": [
                "healthy",
                "warning",
                "critical"
            ],
            "x-enum-varnames": [
                "StatusHealthy",
                "StatusWarning",
                "StatusCritical"
            ]
        },
        "github_com_MD2SA_backup-manager_internal_monitor.HealthSummary": {
            "type": "object",
            "properties": {
                "active_profiles": {
                    "type": "integer"
                },
                "last_execution_status": {
                    "type": "string"
                },
                "last_success": {
                    "type": "string"
                },
                "next_scheduled": {
                    "type": "string"
                },
                "overdue_profiles": {
                    "type": "integer"
                },
                "status": {
                    "$ref": "#/definitions/github_com_MD2SA_backup-manager_internal_monitor.HealthStatus"
                },
                "total_storage_used": {
                    "type": "integer"
                }
            }
        },
        "github_com_MD2SA_backup-manager_internal_pkg_apiutil.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Backup Manager API",
	Description:      "This is a backup management server for Postgres databases.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
